// FILTERS
export const CLEAR_CONTRACT_FILTER = 'CLEAR_CONTRACT_FILTER'
export const CLEAR_DATE_FILTER = 'CLEAR_DATE_FILTER'
export const CLEAR_GROUP_FILTER = 'CLEAR_GROUP_FILTER'
export const CLEAR_KEYWORD_FILTER = 'CLEAR_KEYWORD_FILTER'
export const SAVE_FILTERS = 'SAVE_FILTERS'

// JOBS
export const FETCH_JOBS = 'FETCH_JOBS'

// MODALE
export const OPEN_MODALE = 'OPEN_MODALE'
export const CLOSE_MODALE = 'CLOSE_MODALE'
